### ISSUE TITLE
Blender 4.0

### ISSUE THREAD

**Issue by riouxr** [NicSJ/FixColorspace#1]
Hey Blender Bob here! Someone wrote in the comments that the addon doesn't work with Blender 4. Can you check it out please?

**Comment by NicSJ** [comment]
I've asked for more details in the YouTube comments. It works fine for me. It's a bit hard to help people when they don't give details, and just say it's not working. I'll try my best to find the issue, if there is one.

**Comment by NicSJ** [comment]
I haven't received any more information about this. I'm considering this closed.
